### ISSUE TITLE
[BUG] Sneak peek on song change.

### ISSUE THREAD

**Issue by david-mateogit** [TheBoredTeam/boring.notch#211]
**Is your feature request related to a problem? Please describe.**
Sneak peek is not triggering when changing songs. It only shows when you play a song after pause but not on change.

**Describe the solution you'd like**
It would be nice if there was a toggle to show sneak peek on every song / media change but disable that when using fullscreen apps.

Thanks to all working on this project.

**Comment by Alexander5015** [comment]
Could you please provide for information about which app/media source you are experiencing this on?

**Comment by david-mateogit** [comment]
Using Spotify on Mac OS 15.1. 
Sneak peek works when playing after pausing a song but not when you change the song via the keyboard keys or spotify's own controls or when it changes the songs after completing the current one.

Please let me know if you need more info. 
Thanks.

**Comment by Alexander5015** [comment]
This is now fixed in the `dev` branch and will be included in the next update

**Comment by david-mateogit** [comment]
Great. 
I was playing with the main branch and managed to fix it too. 
I also changed things a bit to be able to modify the sneak peak duration.
That gives me enough time to read the song text.
<img width="663" alt="Screenshot 2024-11-19 at 9 00 18 PM" src="https://github.com/user-attachments/assets/e6cea5c9-ebf9-40c4-a7b3-7f5619e41ae3">

**Comment by rodolforfq** [comment]
Was this included in the latest (2.5) release? It still doesn't work for me.

**Comment by david-mateogit** [comment]
Seems it was not. 
Not working for me on the latest version either.
