### ISSUE TITLE
[Bug] Notch appears in incorrect location on M3 Macbook Air after waking from sleep

### ISSUE THREAD

**Issue by rdegges** [TheBoredTeam/boring.notch#283]
### What happened? What are the steps to reproduce the issue?

I can't reproduce this 100% of the time, but I've been using the boring notch for a couple of weeks now on my M3 Macbook Air (running the latest OSX version, Sequoia 15.2), and what happens is that randomly, after opening the lid of my laptop, the notch will be in the incorrect position.

It seems to appear perfectly below the real notch, and offset to the right by ~50%.

![picture of boring notch incorrectly placed](https://github.com/user-attachments/assets/f92176c7-5e61-4e38-835e-1491b08c31c2)

The image above demonstrates what I mean -- it's off center (although it's hard to tell since you can't see the real notch directly).

Here's another picture from my phone, which clearly demonstrates it:

![phone pictures of boring notch incorrectly placed](https://github.com/user-attachments/assets/21d4b253-724b-4902-8529-a22da22a6e2f)

### What did you expect to happen?

For the notch to appear in the same location as it does upon normal launch.

### BoringNotch Version

2.3

### MacOS Version

Sequoia 15.2

### Checks

- [X] I haven't found any duplicates with my issue.

**Comment by rdegges** [comment]
NOTE: To fix this currently, I just have to quit and restart the notch. No biggie, but it's a bit annoying as this happens a few times a day.

**Comment by oleajan** [comment]
i think this is the same as #219 and is already been fixed at #221 that will be included in the next release

**Comment by rdegges** [comment]
Hi @oleajan, after the most recent release (I'm on 2.5) I'm still seeing this behavior.
