### ISSUE TITLE
[Bug] the media controls do not work efficiently for Spotify

### ISSUE THREAD

**Issue by yashrajsinghyps** [TheBoredTeam/boring.notch#638]
### What happened? What are the steps to reproduce the issue?

media controls do not work efficiently for Spotify and the updater also has some issues

### What did you expect to happen?

album art of songs for spotify not showing

### BoringNotch Version

2.6

### macOS Version

macos 26 developer beta 4

### Relevant log output

```shell

```

### Checks

- [x] I haven't found any duplicates with my issue.

**Comment by Ein-Tim** [comment]
What about using the latest version? This has been fixed with 2.7.

https://github.com/TheBoredTeam/boring.notch/releases/tag/v2.7-rc.1

**Comment by luthfiaas** [comment]
I want to add, the issue is still there for me when clicking shuffle button at the notch, its not giving the red shuffle icons. I need to hover back to make it appear. (it have the same problem when I click un-shuffle)

but it work nicely on repeat button. Thank you in advance!

Notch Version: Flying Rabbit 2.7-rc.1
MacOS Verson: Sequioa 15.5

Here I attach what actually happened: [screenshot](https://www.notion.so/image/attachment%3A404df76e-7ffb-4ad3-8083-a6f29015df25%3Aimage.png?table=block&id=245ef300-e9b1-80d2-a031-c4079955f710&spaceId=34b76465-ab9b-482a-987d-f91aae67b835&width=2000&userId=31f8e946-0cbf-4c24-be69-6a82839ea32c&cache=v2)
